version: "3"
services:
  test_database:
    image: mysql:8.0.1
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

  docker:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - test_database